//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeVentas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.Factura1 = new HashSet<Factura>();
        }
    
        public string IDCompra { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<int> DNI { get; set; }
        public Nullable<int> IDPedido { get; set; }
        public string IDFactura { get; set; }
        public Nullable<int> IDProducto { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Pedidos Pedidos { get; set; }
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura1 { get; set; }
    }
}
